---
Title: Build a Robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Build a Robot
description: Learn how to position images to make your own robot.
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introduction
- title: Giving your robot eyes
- title: Giving your robot a mouth
- title: 'Challenge: Design your own robot'
- title: 'Challenge: Add your own images'

