---
Title: Xây dựng một robot
hero_image: images/build-a-robot.png
theme: màu tím
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, thiết kế-1, lập trình-0, Phys-comp-0, sản xuất-0, cộng đồng-0
title: Xây dựng một robot
description: Tìm hiểu cách định vị hình ảnh để thiết kế robot của riêng bạn
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: nghệ thuật
technologies: html-css-javascript
site_areas: các dự án
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những thứ bạn sẽ cần
  - 
    title: Thêm mắt cho robot của bạn
  - 
    title: Thêm miệng cho robot của bạn
  - 
    title: 'Thử thách: tạo thiết kế riêng của bạn'
  - 
    title: 'Thử thách: thêm hình ảnh của riêng bạn'
