---
Title: Xây dựng một robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Xây dựng một robot
description: Tìm hiểu cách định vị hình ảnh để thiết kế robot của riêng bạn
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Giới thiệu
- title: Những thứ bạn sẽ cần
- title: Thêm mắt cho robot của bạn
  completion:
  - engaged
- title: Thêm miệng cho robot của bạn
  completion:
  - internal
- title: 'Thử thách: tạo thiết kế riêng của bạn'