---
Title: Izrada robota
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Izrada robota
description: Saznajte kako postaviti slike kako biste dizajnirali vlastitog robota
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Trebat ćeš
- title: Dajte robotu oči
  completion:
  - engaged
- title: Dajte robotu usta
  completion:
  - internal
- title: 'Izazov: vaš vlastiti dizajn'