---
Title: Einen Roboter bauen
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Einen Roboter bauen
description: Lerne Bilder zu positionieren, um deinen eigenen Roboter zu entwerfen
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Was du brauchst
- title: Gib deinem Roboter Augen
  completion:
  - engaged
- title: Gib deinem Roboter einen Mund
  completion:
  - internal
- title: 'Aufgabe: Entwerfe dein eigenes Gesicht'
- title: 'Aufgabe: Deine eigenen Bilder hinzufügen'
