---
Title: Einen Roboter bauen
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Einen Roboter bauen
description: Lerne Bilder zu positionieren, um deinen eigenen Roboter zu entwerfen
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchst
  - 
    title: Gib deinem Roboter Augen
  - 
    title: Gib deinem Roboter einen Mund
  - 
    title: 'Aufgabe: Dein eigenes Design'
  - 
    title: 'Aufgabe: Füge ein eigenes Bilder hinzu'

