---
Title: Construiește un robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Construiește un robot
description: Află cum să poziționezi imaginile pentru a-ți proiecta propriul robot
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: De ce vei avea nevoie
  - 
    title: Pune-i ochii robotului tău
    completion:
      - engaged
  - 
    title: Pune-i gura robotului tău
    completion:
      - internal
  - 
    title: 'Provocare: modelul tău propriu'
  - 
    title: 'Provocare: adaugă propriile tale imagini'
