---
Title: Build a robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Construye un robot
description: Aprende cómo colocar imágenes para diseñar tu propio robot
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: arte
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Giving your robot eyes
  - 
    title: Dándole una boca a tu robot
  - 
    title: 'Desafío: tu propio diseño'
  - 
    title: 'Desafío: añade tus propias imágenes'
