---
Title: Konstruiši robota
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Konstruiši robota
description: Nauči kako da pozicioniranjem slika dizajniraš sopstvenog robota
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Šta će ti biti potrebno
  - 
    title: Dodavanje očiju
  - 
    title: Dodavanje usta
  - 
    title: 'Izazov: tvoj sopstveni dizajn'
  - 
    title: 'Izazov: dodaj svoje slike'
