---
Title: Construire un Robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Construire un Robot
description: Apprenez à positionner des images pour fabriquer votre propre robot
original_url: https://codeclubprojects.org/en-GB/webdev/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: Donner des yeux à votre robot
- title: Donner une bouche à votre robot
- title: 'Défi: Concevez votre propre robot'
- title: 'Défi: Ajoutez vos propres images'