---
Title: Costruire un robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Costruire un robot
description: Impara a posizionare le immagini per costruire il tuo robot
original_url: https://projects.raspberrypi.org/en/projects/build-a-robot
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Disegnare gli occhi al robot
  - 
    title: Disegnare la bocca del robot
  - 
    title: 'Sfida: Progetta il tuo robot'
  - 
    title: 'Sfida: Aggiungi le tue immagini'
  - 
    title: 'Challenge: add your own images'
