---
Title: Costruisci un robot
hero_image: images/build-a-robot.png
theme: violet
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Costruisci un robot
description: Scopri come posizionare le immagini per progettare il tuo robot
original_url: https://projects.raspberrypi.org/en/projects/build-a-robot
interests: arte
technologies: html-css-javascript
site_areas: progetti
hardware: ''
software: html/css
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Requisiti
  - 
    title: Disegnare gli occhi del robot
  - 
    title: Disegnare la bocca del robot
  - 
    title: 'Sfida: Aggiungi le tue immagini'
  - 
    title: 'Sfida: aggiungi le tue immagine'
